// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsrxxtnlqlqevqbuuktc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzcnh4dG5scWxxZXZxYnV1a3RjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyMjU1NTMsImV4cCI6MjA1NDgwMTU1M30.BHuSPKxXj6DZsXxhnNonvXTIuRf3FjSEzvBThAJsI08";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);